name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint • Type • Test (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies (dev + test)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,test]"

      - name: Ruff format check
        run: |
          ruff format --check .

      - name: Ruff lint
        run: |
          ruff check .

      - name: Mypy
        run: |
          mypy .

      - name: Pytest
        env:
          PYTHONHASHSEED: "0"
        run: |
          pytest -q

  smoke:
    name: API Smoke
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . uvicorn[standard]

      - name: Launch API
        run: |
          nohup python -m uvicorn services.api:app --host 127.0.0.1 --port 8001 > uvicorn.log 2>&1 &
          for i in {1..25}; do
            curl -fsS http://127.0.0.1:8001/health && break || sleep 0.5
          done

      - name: Probe endpoints
        run: |
          curl -fsS http://127.0.0.1:8001/health
          curl -fsS http://127.0.0.1:8001/metrics | head -n 20

